CREATE TABLE `oevisit` (
`id` INT(10) NOT NULL AUTO_INCREMENT,
`sex` TEXT NULL,
`age` INT(10) NULL DEFAULT NULL,
PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=78;
